
"EBNF defined in itself." {
  syntax     = [ title ] , "{" , { rule } , "}" , [ comment ] .
  rule       = identifier , ( "=" | ":" | ":==" ) , expression , ( "." | ";" ) .
  expression = term { "|" , term } .
  term       = factor { ',' , factor } .
  factor     = literal
             | range
             | "[" , expression , "]"
             | "(" , expression , ")"
             | "{" , expression , "}" .

  identifier = letter , { letter | digit | "_" , letter } .
  title      = string_literal .
  comment    = string_literal .

  concatenate = ',' .

  definition_list_start = '=' | ':=='  .

  definition_separator = '|' .

  start_repeat = '{' .

  end_repeat = '}' .

  start_option = '[' .

  end_option = ']' .

  start_group = '(' .

  end_group = ')' .

  terminator = '.' | ';' .

  single_quote = "'" .

  double_quote = '"' .

  range_operator = '..' .

  letter     = "a" .. "z" | "A" .. "Z"

  digit      = "0" .. "9"

  # composite tokens

  character  = letter | digit | "+" | "-" | "*" | "/" | "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">" | "=" | "|" | "." | "," | ";" .

  char_literal      = "'" , character , "'" | '"' , character , '"'

  string_literal     = "'" , character , { character } , "'" | '"' , character , { character } , '"' .

  range       = char_literal ".." char_literal .

  identifier = letter, { letter | digit }
}
