"very simple c

description intentionally on multiple lines

"" ." {
    Root = {ClassDeclaration};
    ClassDeclaration = ['public'], 'class', Identifier, '{', Members, '}';

    Members = {Member};
    Member = ClassDeclaration | FieldDeclaration;
    FieldDeclaration = ['public'], Type, Identifier, ';';
    Type = Identifier;
}
