"EBNF defined in itself." {
  syntax            = [ syntax_title ] , '{' , {rule_comment}, { rule , {rule_comment} } , '}' , [ syntax_comment ] .
  syntax_title      = string_expression .
  rule_comment      = '(*', { COMMENT_CHARACTER }, '*)' .
  rule              = identifier , ( '=' | ':' | ':==' ) , expression , ( '.' | ';' ) .
  expression        = term { '|' , term } .
  term              = factor { ',' , factor } .
  factor            = IDENTIFIER
                    | string_expression
                    | special_expression
                    | optional_expression
                    | grouped_expression
                    | repeated_expression .

  string_expression =  "'", {FIRST_TERMINAL_CHARACTER}, "'" | '"', {SECOND_TERMINAL_CHARACTER}, '"'
  special_expression  = '?',  {SPECIAL_SEQUENCE_CHARACTER}, '?'
  optional_expression = '[' , expression , ']' .
  grouped_expression  = '(' , expression , ')' .
  repeated_expression  = '{' , expression , '}' .

  syntax_comment    = string_expression .

  IDENTIFIER        = LETTER , { [ '_' ], ( LETTER | DECIMAL_DIGIT ) } .

  (*
    need to define :
        FIRST_TERMINAL_CHARACTER,
        SECOND_TERMINAL_CHARACTER,
        SPECIAL_SEQUENCE_CHARACTER
  *)
} "For more information see http://standards.iso.org/ittf/PubliclyAvailableStandards/s026153_ISO_IEC_14977_1996(E).zip"
